from abc import ABC, abstractmethod
from typing import Callable, Coroutine

class BaseTransport(ABC):
    @abstractmethod
    def event_bind_connected(self, callback: Callable): ...
    @abstractmethod
    def event_bind_disconnect(self, callback: Callable): ...
    @abstractmethod
    async def connect(self): ...
    @abstractmethod
    async def disconnect(self): ...
    @abstractmethod
    async def send(self, data: bytes): ...
    @abstractmethod
    async def listen(self, callback: Callable[[bytes], Coroutine]): ...
    @property
    @abstractmethod
    def is_connected(self) -> bool: ...

    @abstractmethod
    def config(self, config: dict): ...
